package io.carml.logicalview.duckdb;

import io.carml.logicalsourceresolver.ResolvedSource;
import io.carml.logicalview.EvaluationContext;
import io.carml.logicalview.LogicalViewEvaluator;
import io.carml.logicalview.ViewIteration;
import io.carml.model.LogicalView;
import io.carml.model.Source;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.function.Function;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import reactor.core.publisher.Flux;
import reactor.core.publisher.FluxSink;
import reactor.core.scheduler.Schedulers;

/**
 * A {@link LogicalViewEvaluator} that compiles a {@link LogicalView} to a DuckDB SQL query via
 * {@link DuckDbViewCompiler}, executes it against a DuckDB JDBC {@link Connection}, and streams the
 * result rows as {@link ViewIteration}s.
 *
 * <p>Since DuckDB JDBC is blocking, the query execution is offloaded to a bounded elastic thread
 * pool via {@link Schedulers#boundedElastic()}, preserving the reactive API contract. From a
 * downstream consumer's perspective, this evaluator produces a standard {@code Flux<ViewIteration>}
 * indistinguishable from a fully non-blocking evaluator.
 *
 * <p>The {@code sourceResolver} parameter from the {@link LogicalViewEvaluator} interface is not
 * used by this evaluator. DuckDB reads data files directly via functions such as
 * {@code read_json_auto}, {@code read_csv_auto}, and {@code read_parquet}.
 *
 * <p><strong>Thread safety:</strong> This evaluator is not thread-safe. The provided
 * {@link Connection} must not be shared with concurrent callers. DuckDB JDBC connections are
 * single-threaded; concurrent use will result in undefined behavior.
 */
@Slf4j
@AllArgsConstructor
public class DuckDbLogicalViewEvaluator implements LogicalViewEvaluator {

    private final Connection connection;

    @Override
    public Flux<ViewIteration> evaluate(
            LogicalView view, Function<Source, ResolvedSource<?>> sourceResolver, EvaluationContext context) {
        // SQL is generated by jOOQ DSL from the LogicalView model, not from user input
        var sql = DuckDbViewCompiler.compile(view, context);

        LOG.debug("Executing DuckDB query for view [{}]", view.getResourceName());

        return Flux.<ViewIteration>create(sink -> executeQuery(sink, sql, view))
                .subscribeOn(Schedulers.boundedElastic());
    }

    @SuppressWarnings("java:S2077") // SQL is generated by jOOQ, not from user input
    private void executeQuery(FluxSink<ViewIteration> sink, String sql, LogicalView view) {
        try (var statement = connection.createStatement();
                var resultSet = statement.executeQuery(sql)) {
            var columnDescriptor = resolveColumns(resultSet);

            emitRows(sink, resultSet, columnDescriptor);

            sink.complete();
        } catch (SQLException e) {
            LOG.debug("DuckDB query failed for view [{}]: {}", view.getResourceName(), sql);
            sink.error(new RuntimeException(
                    "Failed to execute DuckDB query for view [%s]".formatted(view.getResourceName()), e));
        }
    }

    private ColumnDescriptor resolveColumns(ResultSet resultSet) throws SQLException {
        var metadata = resultSet.getMetaData();
        var columnCount = metadata.getColumnCount();
        var columnNames = new ArrayList<String>(columnCount);
        var idxColumn = -1;

        for (var i = 1; i <= columnCount; i++) {
            var colName = metadata.getColumnLabel(i);
            if (DuckDbViewCompiler.INDEX_COLUMN.equals(colName)) {
                idxColumn = i;
            } else {
                columnNames.add(colName);
            }
        }

        return new ColumnDescriptor(columnNames, idxColumn);
    }

    private void emitRows(FluxSink<ViewIteration> sink, ResultSet resultSet, ColumnDescriptor columns)
            throws SQLException {
        while (resultSet.next()) {
            if (sink.isCancelled()) {
                break;
            }

            var index = columns.idxColumn > 0 ? resultSet.getInt(columns.idxColumn) : 0;
            var values = new LinkedHashMap<String, Object>(columns.names.size());
            for (var colName : columns.names) {
                values.put(colName, resultSet.getObject(colName));
            }

            sink.next(new DuckDbViewIteration(index, values));
        }
    }

    private record ColumnDescriptor(List<String> names, int idxColumn) {}
}
