package io.carml.logicalview.duckdb;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.LinkedHashMap;
import java.util.Map;
import lombok.extern.slf4j.Slf4j;

/**
 * Caches DuckDB source SQL expressions as temporary tables, ensuring each unique source is read only
 * once. When two logical views share the same source (e.g., the same {@code read_json_auto('file.json')}
 * call), the first encounter materializes the data into a temp table and subsequent encounters reuse
 * it.
 *
 * <p>The cache key is the compiled {@code sourceSql} string. If two views produce identical source
 * SQL, they share the same temp table. Different iterators or source files produce different SQL and
 * therefore different tables.
 *
 * <p>Temp tables live on the DuckDB {@link Connection} and are automatically dropped when the
 * connection closes. {@link #clear(Connection)} can be called for explicit cleanup.
 *
 * <p><strong>Thread safety:</strong> This class is not thread-safe. It must be used from a single
 * thread, consistent with DuckDB's single-threaded JDBC connection model.
 */
@Slf4j
class DuckDbSourceTableCache {

    private static final String TABLE_PREFIX = "__carml_src_";

    private final Map<String, String> cache = new LinkedHashMap<>();

    private int counter = 0;

    /**
     * Returns the temp table name for the given source SQL, creating it if necessary. On first
     * encounter, executes {@code CREATE TEMP TABLE "<name>" AS SELECT * FROM <sourceSql>} to
     * materialize the source data.
     *
     * <p>If table creation fails (e.g., due to insufficient memory for large sources), returns
     * {@code null} to signal that the caller should use the raw source SQL directly. The failure is
     * recorded so that subsequent calls for the same source SQL return {@code null} immediately
     * without retrying.
     *
     * @param sourceSql the source SQL expression (e.g., {@code read_json_auto('file.json')})
     * @param connection the DuckDB JDBC connection
     * @return the temp table name (unquoted), or {@code null} if materialization failed
     */
    @SuppressWarnings({
        "java:S2077", // sourceSql is generated by DuckDbSourceHandler, not from user input
        "java:S3649" // same: no user-supplied input reaches this SQL
    })
    String getOrCreateTable(String sourceSql, Connection connection) {
        if (cache.containsKey(sourceSql)) {
            var existing = cache.get(sourceSql);
            if (existing != null) {
                LOG.debug("Reusing cached source table [{}] for: {}", existing, sourceSql);
            }
            return existing;
        }

        var tableName = TABLE_PREFIX + counter++;
        LOG.debug("Creating temp source table [{}] for: {}", tableName, sourceSql);

        try (var statement = connection.createStatement()) {
            statement.execute(
                    "CREATE OR REPLACE TEMP TABLE \"%s\" AS SELECT * FROM %s".formatted(tableName, sourceSql));
        } catch (SQLException e) {
            LOG.warn(
                    "Failed to materialize source into temp table, falling back to direct source read: {}",
                    e.getMessage());
            cache.put(sourceSql, null);
            return null;
        }

        cache.put(sourceSql, tableName);
        return tableName;
    }

    /**
     * Drops all cached temp tables from the connection and clears the cache. Called defensively
     * before the connection is closed.
     *
     * @param connection the DuckDB JDBC connection
     */
    void clear(Connection connection) {
        for (var tableName : cache.values()) {
            if (tableName == null) {
                continue;
            }
            try (var statement = connection.createStatement()) {
                statement.execute("DROP TABLE IF EXISTS \"%s\"".formatted(tableName));
            } catch (SQLException e) {
                LOG.warn("Failed to drop temp source table [{}]", tableName, e);
            }
        }
        cache.clear();
        counter = 0;
    }

    /** Returns the number of cached source tables. */
    int size() {
        return cache.size();
    }
}
