package io.carml.logicalview.duckdb;

import io.carml.logicalsourceresolver.ResolvedSource;
import io.carml.logicalview.EvaluationContext;
import io.carml.logicalview.LogicalViewEvaluator;
import io.carml.logicalview.ViewIteration;
import io.carml.model.LogicalView;
import io.carml.model.Source;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import lombok.AllArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.eclipse.rdf4j.model.IRI;
import org.eclipse.rdf4j.model.vocabulary.XSD;
import reactor.core.publisher.Flux;
import reactor.core.publisher.FluxSink;
import reactor.core.scheduler.Schedulers;

/**
 * A {@link LogicalViewEvaluator} that compiles a {@link LogicalView} to a DuckDB SQL query via
 * {@link DuckDbViewCompiler}, executes it against a DuckDB JDBC {@link Connection}, and streams the
 * result rows as {@link ViewIteration}s.
 *
 * <p>Since DuckDB JDBC is blocking, the query execution is offloaded to a bounded elastic thread
 * pool via {@link Schedulers#boundedElastic()}, preserving the reactive API contract. From a
 * downstream consumer's perspective, this evaluator produces a standard {@code Flux<ViewIteration>}
 * indistinguishable from a fully non-blocking evaluator.
 *
 * <p>The {@code sourceResolver} parameter from the {@link LogicalViewEvaluator} interface is not
 * used by this evaluator. DuckDB reads data files directly via functions such as
 * {@code read_json_auto}, {@code read_csv_auto}, and {@code read_parquet}.
 *
 * <p><strong>Thread safety:</strong> This evaluator is not thread-safe. The provided
 * {@link Connection} must not be shared with concurrent callers. DuckDB JDBC connections are
 * single-threaded; concurrent use will result in undefined behavior.
 */
@Slf4j
@AllArgsConstructor
public class DuckDbLogicalViewEvaluator implements LogicalViewEvaluator {

    private static final String INDEX_KEY = "#";

    private static final String ORDINAL_SUFFIX = ".#";

    /**
     * Maps DuckDB type strings to XSD datatype IRIs. This covers both {@code json_type()} return
     * values (e.g. {@code "BIGINT"}, {@code "DOUBLE"}) and {@code typeof()} return values for SQL
     * column types (e.g. {@code "INTEGER"}, {@code "FLOAT"}, {@code "DATE"}).
     *
     * <p>Types not in this map (e.g. {@code "VARCHAR"}, {@code "NULL"}, {@code "JSON"}) have no
     * natural RDF datatype. Parameterized types like {@code "DECIMAL(18,3)"} and
     * {@code "TIMESTAMP WITH TIME ZONE"} are handled via prefix matching in
     * {@link #resolveXsdType(String)}.
     */
    private static final Map<String, IRI> DUCKDB_TYPE_TO_XSD = Map.ofEntries(
            // JSON integer types (from json_type())
            Map.entry("BIGINT", XSD.INTEGER),
            Map.entry("UBIGINT", XSD.INTEGER),
            Map.entry("HUGEINT", XSD.INTEGER),
            Map.entry("UHUGEINT", XSD.INTEGER),
            // SQL integer types (from typeof())
            Map.entry("INTEGER", XSD.INTEGER),
            Map.entry("SMALLINT", XSD.INTEGER),
            Map.entry("TINYINT", XSD.INTEGER),
            Map.entry("UINTEGER", XSD.INTEGER),
            Map.entry("USMALLINT", XSD.INTEGER),
            Map.entry("UTINYINT", XSD.INTEGER),
            // Float/Double types
            Map.entry("DOUBLE", XSD.DOUBLE),
            Map.entry("FLOAT", XSD.DOUBLE),
            // Boolean
            Map.entry("BOOLEAN", XSD.BOOLEAN),
            // Date/Time types
            Map.entry("DATE", XSD.DATE),
            Map.entry("TIME", XSD.TIME),
            Map.entry("TIMESTAMP", XSD.DATETIME),
            // Binary
            Map.entry("BLOB", XSD.HEXBINARY));

    private final Connection connection;

    @Override
    public Flux<ViewIteration> evaluate(
            LogicalView view, Function<Source, ResolvedSource<?>> sourceResolver, EvaluationContext context) {
        // SQL is generated by jOOQ DSL from the LogicalView model, not from user input
        var sql = DuckDbViewCompiler.compile(view, context);

        LOG.debug("Executing DuckDB query for view [{}]", view.getResourceName());

        return Flux.<ViewIteration>create(sink -> executeQuery(sink, sql, view))
                .subscribeOn(Schedulers.boundedElastic());
    }

    @SuppressWarnings("java:S2077") // SQL is generated by jOOQ, not from user input
    private void executeQuery(FluxSink<ViewIteration> sink, String sql, LogicalView view) {
        try (var statement = connection.createStatement();
                var resultSet = statement.executeQuery(sql)) {
            var columnDescriptor = resolveColumns(resultSet);

            emitRows(sink, resultSet, columnDescriptor);

            sink.complete();
        } catch (SQLException e) {
            LOG.debug("DuckDB query failed for view [{}]: {}", view.getResourceName(), sql);
            sink.error(new RuntimeException(
                    "Failed to execute DuckDB query for view [%s]".formatted(view.getResourceName()), e));
        }
    }

    private ColumnDescriptor resolveColumns(ResultSet resultSet) throws SQLException {
        var metadata = resultSet.getMetaData();
        var columnCount = metadata.getColumnCount();
        var valueColumns = new ArrayList<String>(columnCount);
        var typeColumns = new ArrayList<String>();
        var idxColumn = -1;

        for (var i = 1; i <= columnCount; i++) {
            var colName = metadata.getColumnLabel(i);
            if (DuckDbViewCompiler.INDEX_COLUMN.equals(colName)) {
                idxColumn = i;
            } else if (colName.endsWith(DuckDbSourceStrategy.TYPE_SUFFIX)) {
                typeColumns.add(colName);
            } else {
                valueColumns.add(colName);
            }
        }

        return new ColumnDescriptor(valueColumns, typeColumns, idxColumn);
    }

    private void emitRows(FluxSink<ViewIteration> sink, ResultSet resultSet, ColumnDescriptor columns)
            throws SQLException {
        while (resultSet.next()) {
            if (sink.isCancelled()) {
                break;
            }

            // ROW_NUMBER() OVER() is 1-based; convert to 0-based for RML-LV "#" semantics
            var rawIndex = columns.idxColumn > 0 ? resultSet.getInt(columns.idxColumn) : 0;
            var zeroBasedIndex = rawIndex > 0 ? rawIndex - 1 : 0;
            var values = new LinkedHashMap<String, Object>(columns.valueNames.size() + 1);
            values.put(INDEX_KEY, zeroBasedIndex);
            for (var colName : columns.valueNames) {
                values.put(colName, resultSet.getObject(colName));
            }

            var naturalDatatypes = resolveNaturalDatatypes(resultSet, columns, values);

            sink.next(new DuckDbViewIteration(zeroBasedIndex, values, naturalDatatypes));
        }
    }

    /**
     * Resolves natural RDF datatypes from the type companion columns and ordinal columns in the
     * result set. Maps DuckDB {@code json_type()} string values to XSD IRIs and assigns
     * {@code xsd:integer} to all index and ordinal columns.
     */
    private static Map<String, IRI> resolveNaturalDatatypes(
            ResultSet resultSet, ColumnDescriptor columns, Map<String, Object> values) throws SQLException {
        var naturalDatatypes = new LinkedHashMap<String, IRI>();

        // The "#" index key always has xsd:integer
        naturalDatatypes.put(INDEX_KEY, XSD.INTEGER);

        // All ordinal columns (.#) have xsd:integer
        for (var colName : values.keySet()) {
            if (colName.endsWith(ORDINAL_SUFFIX)) {
                naturalDatatypes.put(colName, XSD.INTEGER);
            }
        }

        // Map type companion columns to XSD datatypes
        for (var typeCol : columns.typeNames) {
            var duckDbType = resultSet.getString(typeCol);
            if (duckDbType != null) {
                var xsdType = resolveXsdType(duckDbType);
                if (xsdType != null) {
                    // Strip the TYPE_SUFFIX to get the field name this type applies to
                    var fieldName = typeCol.substring(0, typeCol.length() - DuckDbSourceStrategy.TYPE_SUFFIX.length());
                    naturalDatatypes.put(fieldName, xsdType);
                }
            }
        }

        return naturalDatatypes;
    }

    /**
     * Resolves a DuckDB type string to an XSD datatype IRI. First attempts an exact match in the
     * type map. If no exact match is found, falls back to prefix matching for parameterized types
     * such as {@code "DECIMAL(18,3)"} and {@code "TIMESTAMP WITH TIME ZONE"}.
     *
     * @param duckDbType the type string from DuckDB's {@code json_type()} or {@code typeof()}
     * @return the corresponding XSD IRI, or {@code null} if no mapping exists
     */
    private static IRI resolveXsdType(String duckDbType) {
        var xsdType = DUCKDB_TYPE_TO_XSD.get(duckDbType);
        if (xsdType != null) {
            return xsdType;
        }
        if (duckDbType.startsWith("DECIMAL")) {
            return XSD.DECIMAL;
        }
        if (duckDbType.startsWith("TIMESTAMP")) {
            return XSD.DATETIME;
        }
        // TIME WITH TIME ZONE — must come after TIMESTAMP check to avoid false match
        if (duckDbType.startsWith("TIME")) {
            return XSD.TIME;
        }
        return null;
    }

    private record ColumnDescriptor(List<String> valueNames, List<String> typeNames, int idxColumn) {}
}
